#!/data/data/com.termux/files/usr/bin/bash
pkg update
pkg upgrade
pkg install x11-repo
pkg install termux-x11-nightly
pkg install tur-repo
pkg install pulseaudio
pkg install proot-distro
pkg install wget
pkg install git
pd login debian
apt update -y
apt install sudo nano adduser -y
adduser dani
exit
pd login debian
 wget --tries=5 --retry-connrefused -O ${current_path}/ https://raw.githubusercontent.com/sabamdarif/termux-desktop/main/distro-container-setup
			if [[ ("$1" == "--change" || "$1" == "-c") && ("$2" == "distro" || "$2" == "pd") ]]; then
			sed -i 's/\(call_from_change_d="\)[^"]*/\1y/' "${current_path}/distro-container-setup"
			fi
            chmod +x ${current_path}/distro-container-setup
            . ${current_path}/distro-container-setup
